### ISSUE TITLE
Release date receiving functionality

### ISSUE THREAD

**Issue by JamesDefert891** [nearby-sharing/android#35]
When will the stable version with PC ➜ Android support finally come out?

**Comment by ShortDevelopment** [comment]
The current implementation “works“ in the sense that it successfully transfers data in the scenarios, the testers have tested.

The problem is, that the current code base is full of assumptions / uncertainties that could easily break the app. There might also be a lot of memory leaks.

I really want to fix all these things before calling this “stable”.

See #20

**Comment by ShortDevelopment** [comment]
@JamesDefert891 I know it's been a long time and I certainly got a lot of stuff left to do, but Google is kind of pushing me to release a "stable" version on 01.11.2023 as all android app should target api level 33 by then.

So here you go! 😉
